name = "PoleExploration"
uuid = "6f678a3b-cef4-45cd-8023-1a0e41a40050"
authors = ["Albin Heimerson <albin.heimerson@control.lth.se>"]
version = "0.3.1"

[deps]
ControlSystems = "a6e380b2-a6ca-5380-bf3e-84a91bcd477e"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
SnoopPrecompile = "66db9d55-30c0-4569-8b51-7e840670fc0c"

[compat]
ControlSystems = "1.0"
GLMakie = "0.6"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]