name = "PoleExploration"
uuid = "6f678a3b-cef4-45cd-8023-1a0e41a40050"
authors = ["Albin Heimerson <albin.heimerson@control.lth.se>"]
version = "0.2.0"

[deps]
ControlSystems = "a6e380b2-a6ca-5380-bf3e-84a91bcd477e"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"

[compat]
julia = "1.6"
GLMakie = "0.6"
ControlSystems = "1.0"